모델링 작성
wecode-bootcamp-korea/33-2nd-yakurt-backend pull request #2
Opened 2022-06-08 09:52 UTC by ysang989

user,products,orders,carts,subscriptions,survey,core앱의 models.py 작성

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 모델링 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- orders, products, users, subscriptions, core, carts, survey models.py 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-06-08 10:04 UTC, Kang-kyunghun requested changes

2022-06-08 10:04 UTC, Kang-kyunghun commented on subscriptions/models.py
> +    paymentmethod    = models.ForeignKey('orders.Paymentmethod', on_delete=models.CASCADE)
```suggestion
    payment_method    = models.ForeignKey('orders.Paymentmethod', on_delete=models.CASCADE)
```

2022-06-08 10:04 UTC, Kang-kyunghun commented on survey/models.py
> +    product = models.ManyToManyField('products.Product', through= 'SymptomProduct')
```suggestion
    name     = models.CharField(max_length=200)
    products = models.ManyToManyField('products.Product', through= 'SymptomProduct')
```
- M2M field로 선언한 필드는 복수형으로 해주는 것이 의미상 더 자연스럽습니다.
- = 기준으로 정렬해 주세요.

2022-06-08 10:04 UTC, Kang-kyunghun commented on orders/models.py
> +class Paymentmethod(TimeStampedModel):
```suggestion
class PaymentMethod(TimeStampedModel):
```

2022-06-08 10:44 UTC, ysang989 commented on orders/models.py
> +    subscription = models.ForeignKey('subscriptions.Subscription', on_delete=models.CASCADE)
네 수정했습니다!

2022-06-08 10:44 UTC, ysang989 commented on orders/models.py
> +    paymentmethod    = models.ForeignKey('Paymentmethod', on_delete=models.CASCADE)
수정했습니다!

2022-06-08 10:45 UTC, ysang989 commented on products/models.py
> +        db_table = 'reviews'
수정했습니다

2022-06-08 10:46 UTC, ysang989 commented on subscriptions/models.py
> +    paymentmethod    = models.ForeignKey('orders.Paymentmethod', on_delete=models.CASCADE)
수정했습니다

2022-06-08 10:47 UTC, ysang989 commented on survey/models.py
> +    product = models.ManyToManyField('products.Product', through= 'SymptomProduct')
수정했습니다

2022-06-08 10:47 UTC, ysang989 commented on orders/models.py
> +class Paymentmethod(TimeStampedModel):
수정했습니다

2022-06-08 10:48 UTC, ysang989 commented on subscriptions/models.py
> +    is_subscribing   = models.BooleanField(default=True)
멘토님 해당 is_subscribing 은 정기구독 테이블에서 정기구독을 멈출경우 정기구독 종료로 변경되어야 하기 때문에 작성한 테이블 입니다. 확인부탁드립니다!

2022-06-09 03:32 UTC, Kang-kyunghun commented
LGTM~!

2022-06-09 03:32 UTC, merged