[33기 최혜인]
wecode-bootcamp-korea/33-2nd-yakurt-backend pull request #8
Opened 2022-06-11 05:34 UTC by DDinoBox

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-06-13 01:20 UTC, Kang-kyunghun requested changes

2022-06-13 01:20 UTC, Kang-kyunghun commented on products/views.py
> +from django.views import View
```suggestion
from django.http  import JsonResponse
from django.views import View
```

2022-06-13 01:20 UTC, Kang-kyunghun commented on products/views.py
> +            return JsonResponse({'Message': 'PRODUCT_DOES_NOT_EXIST'})
상태코드 추가해 주세요.
```suggestion
        if not Product.objects.filter(id=product_id).exists():
            return JsonResponse({'Message': 'PRODUCT_DOES_NOT_EXIST'}, status=404)
```

2022-06-13 01:20 UTC, Kang-kyunghun commented on products/views.py
> +        product = Product.objects.filter(id=product_id)
filter로 가져와서 불필요하게 다시 for문을 돌리는 이유가 있을까요?
get으로 바로 객체를 가져와서 리스트가 아닌 딕셔너리로 주면 좋을 것 같습니다.

2022-06-13 01:20 UTC, Kang-kyunghun commented on products/tests.py
> +class ProductDetailTest(TestCase):
성공 사례에 대한 test 잘 진행 하셨습니다.
view 코드에 있는 실패 사례에 대해서도 test 하나 추가해 주세요.

2022-06-13 22:22 UTC, DDinoBox commented on products/views.py
> +from django.views import View
수정했습니다!

2022-06-13 22:23 UTC, DDinoBox commented on products/views.py
> +        product = Product.objects.filter(id=product_id)
프론트 요청으로 인한 리스트 형태입니다! ㅠㅠ 다음에는 딕셔너리로 처리 할 수 있도록 프론트와 협의 하겠습니다!

2022-06-13 22:23 UTC, DDinoBox commented on products/tests.py
> +class ProductDetailTest(TestCase):
실패 사례 추가 후 unit test OK 확인 했습니다!

2022-06-14 05:14 UTC, Kang-kyunghun commented
LGTM

2022-06-14 05:14 UTC, merged